const replaceAllUnicode = (str) => {
  str = str.replaceAll('&quot;', '"');
  // &amp;
  str = str.replaceAll('&amp;', '&');
  // &lt;
  str = str.replaceAll('&lt;', '<');
  // &gt;
  str = str.replaceAll('&gt;', '>');
  // &#039;
  str = str.replaceAll('&#039;', '\'');
  // &#x27;
  str = str.replaceAll('&#x27;', '\'');
  // &#x2F;
  str = str.replaceAll('&#x2F;', '/');
  // &#x60;
  str = str.replaceAll('&#x60;', '`');
  // &#x3D;
  str = str.replaceAll('&#x3D;', '=');
  // &#x3A;
  str = str.replaceAll('&#x3A;', ':');
  // &#x3B;
  str = str.replaceAll('&#x3B;', ';');
  // &#x3C;
  str = str.replaceAll('&#x3C;', '<');
  // &#x3E;
  str = str.replaceAll('&#x3E;', '>');
  // &#x5B;
  str = str.replaceAll('&#x5B;', '[');
  // &#x5D;
  str = str.replaceAll('&#x5D;', ']');
  // &#x7B;
  str = str.replaceAll('&#x7B;', '{');
  // &#x7D;
  str = str.replaceAll('&#x7D;', '}');
  // &#x5C;
  str = str.replaceAll('&#x5C;', '\\');
  // &#x7E;
  str = str.replaceAll('&#x7E;', '~');
  // &#x5E;
  str = str.replaceAll('&#x5E;', '^');
  // &#x7C;
  str = str.replaceAll('&#x7C;', '|');
  // &#x5F;
  str = str.replaceAll('&#x5F;', '_');
  // &#x7F;
  str = str.replaceAll('&#x7F;', '\u007F');
  // &#xA0;
  str = str.replaceAll('&#xA0;', '\u00A0');
  // &#xA1;
  str = str.replaceAll('&#xA1;', '\u00A1');
  return str;
};

export default replaceAllUnicode;
